version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - "8080:8080" # Expose server on port 8080
    volumes:
      - ./server:/app # Sync server folder for live updates
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite-db
    volumes:
      - ./db:/db # Persist database files
    command: ["sqlite3", "/db/database.db"]
