version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/db:/app/db
      - ./client:/app/client
    environment:
      - GO_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/cotacao"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
